### PR TITLE
collect and display payment attempts, reasons for failure and if automatically retry is going to happen #638

### PR DESCRIPTION
**Pull request by chrisjsimpson**
Ref #683

- listen for payment_intent.payment_failed webhook event

### CODE REVIEW

**Comment by chrisjsimpson** [comment]
@lgtm-com[bot] 👀

**Comment by chrisjsimpson** [comment]
https://github.com/github/codeql/issues/7497

**Comment by chrisjsimpson** [comment]
> Ref #683
> 
> * listen for payment_intent.payment_failed webhook event

Listening for failed payment events was reverted at this time, instead queried at show-subscriber time. Not needed at this time.

**Comment by joeltejeda** [comment]
#786

**Pull request merged**
