### PR TITLE
First version for this problem

### PR DESCRIPTION
**Pull request by schumskie**
Check this, and let me know if I need something to change

### CODE REVIEW

**Comment by chrisjsimpson** [comment]
Lgtm! Thanks @schumskie 

127 0 0 1_5000_admin_subscribers(Pixel 2)

**Comment by chrisjsimpson** [comment]
Sorry I was too quick, on second look- there is a *lot* of repetition here, which should be avoided where possible

**Comment by schumskie** [comment]
Okey, I’ll optimize it in the morning. I tought it was an emergency for
some of the clients

суб, 30. јан 2021. у 00:58 chrisjsimpson <notifications@github.com> је
написао/ла:

**Comment by chrisjsimpson** [comment]
Thanks, I have reverted it :+1: https://github.com/Subscribie/subscribie/commit/cc2587932c4eb799432a855023cea7df3efb91de

**Comment by schumskie** [comment]
I've updated code to this branch based on @Anpoli13 suggestions and example. Please take a look :)

**Pull request merged**
